### ISSUE TITLE
C64 into Framemeister Cable

### ISSUE THREAD

**Issue by a7mag3ddon** [c0pperdragon/C64-Video-Enhancement#100]
Hi, is there a standard way to connect the C64 using the TRSS jack to the Framemeister or do i need to purchase a D Terminal to YPbPr cable? These cables are hard to get in UK or expensive to order in. I was using the OSSC for a while but now i have a framemeister thought id try and get it working on 1 device instead of having 2.

Just wanted to check before buying anything.

**Comment by c0pperdragon** [comment]
I have no experience with the Framemeister. Reading the docs, it will accept component video only on the D terminal.  
But you could reprogramm the C64 mod to output RGB directly. Using the composite signal and the audio from the original A/V port and you can actually get all signals needed for SCART for which you may already have some adapter.

When soldering things yourself is not an option, you will need to go with the mentioned D Terminal to YPrPr cable,

**Comment by a7mag3ddon** [comment]
I have bought the D terminal plug but im not getting a picture, the D terminal has a ref, blue and gree phono on it and i connected it to the red, green and blue phono on the TRSS jack which i assume is ok.

Is the there a digram to tell me which phono is what signal out of the C64 TRSS to make sure they match ?

**Comment by a7mag3ddon** [comment]
It looks like my frameister D terminal has some kind of fault on it.

If i was to convert the C64 mod to output RGB instead would it be as good quality video as it is as standard?  its currently amazing on the OSSC. You mentioned composite signals but i thought composite wasnt as good

**Comment by c0pperdragon** [comment]
The composite signal from the A/V connect would only be needed as sync, not as the actual color lines. The color would come from the mod. So the quality with RGB would be just as good with component. You will need to reprogram the palette of the mod using the palette editing tool: https://github.com/Hojo-Norem/c0pperdragon-VIC-II-Palette-editor

**Comment by a7mag3ddon** [comment]
I've just tested my framemeister component port using a pS2 and D cable and that works so it would seem logical that it's the D port that's either not wired correctly or has a problem.

Please can you tell me what signals are coming out the R, G and Blue Phonos from the TRSS jack so I can test with my multimeter that the correct wiring is going to the correct pins on the D terminal ?

Think I'm getting close to it working now.

Thanks

**Comment by a7mag3ddon** [comment]
Another update, ive back traced the wiring from the componenet cable i bought and the G, B and Red phonos all go to the correct pins of the D Terminal so not sure where to go now.

**Comment by a7mag3ddon** [comment]
Closed this issue, was the switch on the rear, i needed to move it accross one!
