### ISSUE TITLE
C64C Board 250469A Compatibility

### ISSUE THREAD

**Issue by ShoresOfNowhere** [c0pperdragon/C64-Video-Enhancement#102]
Hi @c0pperdragon , just to ask if your analog only board is compatible with my C64C 250469A Board...

I should use the short board connection point, right?

Thanks!

**Comment by c0pperdragon** [comment]
Yes to both questions. And using the "short board" option, there is not even a need to add the extra GND wire as this is already provided via one of the 4 input connection points.

**Comment by ShoresOfNowhere** [comment]
@c0pperdragon Thanks for the instantaneous response! :)
