### ISSUE TITLE
Thermal releifs on pad connections

### ISSUE THREAD

**Issue by bwack** [c0pperdragon/C64-Video-Enhancement#13]
Hi. The decoupling caps under the board were hard to solder on the large copper fill. Can you add thermal releif ?

![2019-06-08 21_23_55-Pcbnew — D__Documents_GitHub_C64-Video-Enhancement-master_rfreplacement_rfreplac](https://user-images.githubusercontent.com/11380333/59151466-eb783680-8a33-11e9-95db-c759859d1711.jpg)

C64 Video Enhancement board rev 3

**Comment by c0pperdragon** [comment]
I decided against thermal reliefs to make the the decoupling caps as effective as any possible. Soldering the caps is easier if you take care to first solder the side that is not on the ground plane. Once the cap is firmly attached, the you can heat up the other side for a longe time without trouble.

**Comment by bwack** [comment]
Thanks for the tip!
