### ISSUE TITLE
Troubleshooting with testpattern

### ISSUE THREAD

**Issue by bwack** [c0pperdragon/C64-Video-Enhancement#14]
Hi. Thanks @desaster for recommending to use the test pattern here: https://github.com/c0pperdragon/A-VideoBoard/releases
I can see a pattern on my scope, but not on the TV. It seems to be very slow. Maybe that is it.
The sawtooth sweeps looks fine, so I guess the resistor ladder is ok.

Looking at Y. 100ms/div, 200mV/div
![bilde](https://user-images.githubusercontent.com/11380333/59554611-d22c3880-8fa5-11e9-9a36-65064a333973.png)

Maybe the fpga needs configuring.. ?

**Comment by desaster** [comment]
when powering the board, notice that there are two groundplanes, GND and GNDA. GND1 and GND2 are connected to GNDA. I initially made the mistake of trying to power the board with GNDA instead of GND.

**Comment by bwack** [comment]
Ok. I did that mistake the first time. Now the board is in the C64. I see I have soldered four grounds except GND5. Not sure what to do. Maybe the crystal is wrong.

**Comment by bwack** [comment]
Ouf, I have mounted the crystal wrong..
![bilde](https://user-images.githubusercontent.com/11380333/59555047-f3dcee00-8fac-11e9-8772-fc5602c63e64.png)

![19061520371910494982](https://user-images.githubusercontent.com/11380333/59555070-6948be80-8fad-11e9-9572-85835f8c43c8.jpg)

**Comment by bwack** [comment]
It was the crystal. Now there is picture :) Thanks for help !

**Comment by c0pperdragon** [comment]
Funny thing that the FPGA actually generates a signal without any oscillator at all. It seems that the PLL inside falls back to generating an ultra-low-speed clock (more than 1000 times slower as planned) when not being driven by an external signal.

**Comment by bwack** [comment]
Maybe the VCO in the PLL continues without the lock.. or there is a fallback. I tried to figure out by datasheet, but without luck. Just curious anyway :)
