### ISSUE TITLE
Let's Invade! - Corrupted text and stars in main menu

### ISSUE THREAD

**Issue by desaster** [c0pperdragon/C64-Video-Enhancement#16]
Hi,

I've been testing Firmware 2.3 a bit, and just stumbled on this issue with "Let's Invade!". 

Links:
https://tnd64.blogspot.com/2016/10/run-run-invasion-has-started.html
https://csdb.dk/release/?id=151230

Picture comparision:

![Let's Invade!](https://user-images.githubusercontent.com/631441/60585347-3158be00-9d98-11e9-9725-b4bc1eba8290.jpg)

With the FPGA implementation, there seems to be corruption in the main menu texts, as well as the starry background. The rest of the game seems to have no errors.

**Comment by desaster** [comment]
This is probably related, since there's something funny going on with text. In a finnish game "Alien Bash", the text is also slightly corrupted in the main menu (there seems to be extra pixels). 

Links:
http://www.ntrautanen.fi/computers/commodore/archive/c64_pelit.htm
http://www.ntrautanen.fi/computers/commodore/archive/c64/pelit/alien_bash.prg

**Comment by c0pperdragon** [comment]
I have broken the multi color text mode in the last release, so I just provided a bugfix version on the releases page.

**Comment by desaster** [comment]
tested and confirmed, all fixed!

**Comment by desaster** [comment]
Although with 2.4 I'm now experiencing some major issues with brutality / edgeofdisgrace. I'll make a ticket tomorrow.
