### ISSUE TITLE
Screengarbage and load errors

### ISSUE THREAD

**Issue by bwack** [c0pperdragon/C64-Video-Enhancement#17]
When the vic ii is in the adapter, and i use jiffydos or other fastloader the screen fills with symbols and sometimes a load error appear. Same image on both coomponent and svideo. I have checked the socket and it seems fine. Swapped cias no change. I disconnect ribbon cable to the fpga board and no change. Inserting the vic without adapter no problem.

**Comment by bwack** [comment]
Ok now i have the issue without the adapter. Ill have to repair my computer before i continue.

**Comment by bwack** [comment]
Removed the swinsid ultimate and problem resolved. No idea why..

**Comment by c0pperdragon** [comment]
The VIC adapter board is designed to only disturb the rest of the system as little as possible. Each signal is sensed with one high-impedance input that should draw less than 1 microampere and has an input capacitance of about 5 picofarad. 
But of course when the rest of the system is already on the very edge of stability this tiny difference may actually push it over the edge.

**Comment by bwack** [comment]
Yes. Could have been the drop that filled the bucket. Anyway the computer works fine without the Swinsid Ultimate. I dont think the fault is related. I was concerned that maybe flux residu could cause problems on thr 0.5mm pitch pin, but no..

**Comment by desaster** [comment]
#18 is probably not related, since you were also having issues with A/V out.

**Comment by bwack** [comment]
@desaster. Probably not related. This happened on my computer with and without the vic adapter. No problems after removing the swinsid ultimate.
The early SSU that I have is covered in hot-snot glue. I've heard about glue becoming conductive after a while, but that is just a guess. The glue covers the system bus lines on the SSU board.

**Comment by DeSater** [comment]
@bwack I think you mis-tagged @desaster
