### ISSUE TITLE
Suggestion: HDMI output

### ISSUE THREAD

**Issue by kasbert** [c0pperdragon/C64-Video-Enhancement#20]
What would it take to add HDMI output to the board ?

**Comment by c0pperdragon** [comment]
I thought on HDMI for quite some time already, but it is really a huge effort. The only sensible output format would be 1080p, and this is beyond the capabilities of cheaper FPGAs to produce directly. So an HDMI transmitter chip is needed. And for some reasons, these chips are incredibly difficult to source and for the few that are available, documentation is either non-existent or restricted to commercial partners. But maybe I can learn something from the OSSC project in this regard.

Also audio would become an issue, as HDMI is no fun without it. So an audio ADC needs to be added (maybe could be done by the FPGA itself, but it is still quite difficult).

Considering the additional electronics needed, I may just be able to provide an HDMI-version of the board, but it may be more expensive. The need to cut a larger hole into the case for a connector is probably also not to everyone's liking.
