### ISSUE TITLE
Analog Only BOM

### ISSUE THREAD

**Issue by SkydivinGirl** [c0pperdragon/C64-Video-Enhancement#22]
Is there a BOM for the Analog Only board?  I'd like to give it a try. :)

Thanks!

Heather

**Comment by c0pperdragon** [comment]
I have just uploaded a BOM and a schematic file for the analog-only board into the appropriate doc folder.

**Comment by SkydivinGirl** [comment]
Thank you! I'll be sure to send you a picture once I have one built and installed in a system. :)

Heather
