### ISSUE TITLE
RGB output

### ISSUE THREAD

**Issue by jammi** [c0pperdragon/C64-Video-Enhancement#23]
Hi, does this version still have the option to output RGB (instead of YPbPr)? I'd like to use it with my old Sony Trinitron studio monitor that understands Composite and RGB, but not S-Video and of course not YPbPr either, since that seems to be a feature for modern TVs.

**Comment by c0pperdragon** [comment]
Yes, the mod can be configured to output various forms of RGB.

If your monitor can accept sync-on-green, this would be the easiest method that does not need additional wiring (just the R,G,B lines).

If it needs an extra sync signal (a.k.a RGBS), you can also configure the mod to output plain RGB without any sync signal on the color lines. Then you need to get the sync information from the original luma output on the A/V port. There it again depends on your monitor, if it can accept a luma signal for sync. If yes, you are fine and may only need a passive cable for this.

 If not, then you need some extra method to turn the luma into a pure sync signal (with a sync stripper). Can be done but is an additional step.
