### ISSUE TITLE
The palette registers & software that misbehaves...

### ISSUE THREAD

**Issue by Hojo-Norem** [c0pperdragon/C64-Video-Enhancement#26]
I'm not really expecting a fix for this because proper practice should be to power-cycle your C64 after flashing a palette, but I have found a piece of software that touches the palette registers if they are unlocked:

'Turbocharge' by System 3.  Both the Easyflash CRT version and one from either the C64PP or Gamebase64 originals (can' remember where) behave like this.

Through component once the game loads to the initial title screen the picture goes all pink.  My guess is that the game as aggressively zeros out memory and ends up zeroing out palette register 0.  Luckily that's all it does.

If I spot any more I'll post them here.

**Comment by c0pperdragon** [comment]
Yes, once the registers are unlocked, some random programs may surely be able to damage their contents by accident. I see not how this can be avoided  - the unlocking procedure was a safeguard also against this happening.

**Comment by c0pperdragon** [comment]
Yes, once the registers are unlocked, some random programs may surely be able to damage their contents by accident. I see not how this can be avoided  - the unlocking procedure was a safeguard also against this happening.
