### ISSUE TITLE
PCB for the vic-II adapter

### ISSUE THREAD

**Issue by 8lall0** [c0pperdragon/C64-Video-Enhancement#27]
Hi,

where are the gerbers for the adapter? Thanks! :)

**Comment by c0pperdragon** [comment]
These are in a different (the original) repo:
https://github.com/c0pperdragon/A-VideoBoard/tree/master/c64mod/doc

**Comment by 8lall0** [comment]
Thank you.

PS: i saw that there is another closed issue about that, i'll put this information on the README of this project. Thank you for your awesome work!
