### ISSUE TITLE
Analog only board refdes error

### ISSUE THREAD

**Issue by TMS2764** [c0pperdragon/C64-Video-Enhancement#28]
The analog board reference designators C10 and C29 are swapped on the PCB. According the the schematics, C10 is for composite pin 2 and C29 is for Luma pin 3. The video enhancement board PCB is ok.

![IMG_0257A](https://user-images.githubusercontent.com/56616717/79701964-1eec3a00-826f-11ea-9917-ab9ceebed536.jpg)

**Comment by c0pperdragon** [comment]
Good spot!
I have fixed this in the PCB layout and the gerber files as well.

**Comment by c0pperdragon** [comment]
As this is the first time anyone seems to have actually built this board, it would be very nice if you could tell me how well this works for you (photographs are highly welcome also).

**Comment by TMS2764** [comment]
I think its great. Glad I found this little analog version design of yours. Just what I wanted to replace those rusty RF modulators that just mess up the video signals.

![IMG_0268A](https://user-images.githubusercontent.com/56616717/79809641-ffbcdd80-833e-11ea-99c8-f8f73debb95d.jpg)

I usually use it in S-video mode. Its difficult to capture but the image is super sharp. The moire effects are from the camera capture. There is no such thing when looking at the screen. There are some visible jail bars.

![IMG_0267A](https://user-images.githubusercontent.com/56616717/79809736-46aad300-833f-11ea-93ac-6edde0b50047.jpg)

Here is a closeup of the text.

![IMG_0270A](https://user-images.githubusercontent.com/56616717/79809947-d3559100-833f-11ea-8ed8-5b37eccc2f0b.jpg)

Here is the same text in composite video. Its not quite as sharp. Furthermore, there are some video artifacts that are visible but difficult to capture on camera.

![IMG_0273A](https://user-images.githubusercontent.com/56616717/79810304-c1c0b900-8340-11ea-98c4-0f1ac53edb53.jpg)

I hope this helps. Thanks for the good work.
