### ISSUE TITLE
Connector GPIO1 and RFCON1 overlap

### ISSUE THREAD

**Issue by TMS2764** [c0pperdragon/C64-Video-Enhancement#29]
I am using a shrouded connector for GPIO1 and it is overlapping with the RFCON1 location. I know its not what was intended but I prefer a shrouded connector. It prevents me from plugging the cable backwards. I would recommend moving the connector a little bit toward the edge of the PCB next to the back of the case.

![IMG_0258A](https://user-images.githubusercontent.com/56616717/79702190-02e99800-8271-11ea-8dd0-4e2fa2c01631.jpg)

**Comment by c0pperdragon** [comment]
As this is a very special requirement, I do not actually want to introduce a new PCB revision. Even more so, as the only pin that causes a problem is not even connected to anything on the FPGA board. 
I propose to just clip away this 4th pin.

**Comment by TMS2764** [comment]
Fair enough. Keep it in mind for the next revision.
