### ISSUE TITLE
Order list

### ISSUE THREAD

**Issue by bodgit** [c0pperdragon/C64-Video-Enhancement#3]
(Sorry for cluttering up the other issue)

I found this project via [oshpark](https://oshpark.com) where I think someone must have ordered their own copies of the two PCB's and it has your github repository helpfully printed on the board. 

I was wondering if you had an order list for these? I don't know if you've announced these boards elsewhere so apologies if so. If you've already filled your back orders then I will try and build my own; soldering the QFP for the FPGA is the tricky bit I think I would struggle with.

**Comment by c0pperdragon** [comment]
I don't take any more orders for complete boards and currently I have just enough bare PCBs to build the ones already sold. I am in the process of stocking up a few parts, so I think I will have some spare bits and pieces after I am finished with my list. Maybe I can then throw enough together to be sold as a kit, but I can not tell at the present state.

Soldering this 0.5mm pitch package is indeed quite a challenge. It took me several failed attempts until I got the first one working.
