### ISSUE TITLE
BOM clarification

### ISSUE THREAD

**Issue by TMS2764** [c0pperdragon/C64-Video-Enhancement#30]
C6 and C7 are actually on top of the PCB.

![bom](https://user-images.githubusercontent.com/56616717/79706526-8e6e2380-8287-11ea-81c2-0282a58682f9.jpg)

**Comment by c0pperdragon** [comment]
For the Rev.4 I moved these capacitors to the other side.  I forgot to update the BOM as well. Is now fixed.

**Comment by TMS2764** [comment]
Excellent, thanks.
