### ISSUE TITLE
Firmware

### ISSUE THREAD

**Issue by Icelvlan88** [c0pperdragon/C64-Video-Enhancement#44]
Hello,

If I'm on 2.0, should I upgrade to latest?

Have you considered using a THS7374 for a video amp? There is a big quality difference between them.

**Comment by c0pperdragon** [comment]
2.0 is really old and does not properly support many tricks done in demos or even games. So I would definitly recommend an update.

And yes, I had a look at this amplifier chip, but it is not designed for my intended higher bandwidth. Its filters are adjusted to fit SDTV content to smooth out noise that would not be relevant in a "normal" standard definition picture. But for my intended purpose (pixels so sharp to cut your eyes) this would be a no-go.
