### ISSUE TITLE
Suitable with C64 reloaded?

### ISSUE THREAD

**Issue by marktp75** [c0pperdragon/C64-Video-Enhancement#48]
Hi,

Is your C64 component video mod compatible with C64 Reloaded mk2?

Thanks.

**Comment by c0pperdragon** [comment]
I guess it could be compatible from the point of few of electrical signals.
But the physical layout is very different, so it may be difficult to install the FPGA board. Also the VIC adapter board will probably add too much height to the assembly, given that the ZIF sockets are so high already. You may not be able to close the case.
