### ISSUE TITLE
Analog_only questions

### ISSUE THREAD

**Issue by xiphias256** [c0pperdragon/C64-Video-Enhancement#51]
I've recently ordered the PCB and components for the analog_only board and in that regard I have some questions.
There is very little information about this PCB on your page.

Some people claim that it is dangerous to use this card without connecting GND1 to ground. My experience so far has been that is is only needed for longboards??

It is not clear to me when I need to solder-bridge JPLUM1? I can see on the schematics that it changes resistor values for the circuit, but I don't know for what reason.

Hope you have the time to create a small readme explaining these two things on your github project.

Thanks,
Finn

**Comment by c0pperdragon** [comment]
You can install this mod in a short board by connecting the 2 times 4 pins only, as these already have a GND connection.
JPLUM1 needs to be closed when running with a 12 volt VIC - these are the older variants used in the long boards. This changes the resistor value needed for attenuating the luma signal. For for a short board you will leave this bridge open.
