### ISSUE TITLE
graphics repeat in top border

### ISSUE THREAD

**Issue by lyzanxia** [c0pperdragon/C64-Video-Enhancement#54]
In the game Leviathan (start screen) the cubes are visible in top border, also on several demos some objects are visible in the top border (visuality III for example). Can post video if needed.

**Comment by c0pperdragon** [comment]
Please take a comparision picture of both the component video and the original composite/s-video output.
Also please send me a link to the demo so I can later try this myself.

**Comment by lyzanxia** [comment]
Nervermind, sorry original composite/s-video output is the same...if you wanted to see what I meant https://csdb.dk/release/?id=2536 (but seems to be this way with everyone)
