### ISSUE TITLE
C128 support (#2)

### ISSUE THREAD

**Issue by c0pperdragon** [c0pperdragon/C64-Video-Enhancement#64]
This is a continuation of https://github.com/c0pperdragon/C64-Video-Enhancement/issues/4

**Comment by lolof70** [comment]
Thank you very much for your great support ! Really happy, I will build one for my C64.
Thanks again.

**Comment by lolof70** [comment]
After some more testing, I do not know why, but some times the image is stable, sometimes not.
When it's not stable, there is light movement mostly horizontally or lightly in diagonal.
Moving a bit down to up... Like if it was doing this with the back colours. The rest seems stable.
I thought it came from the PSU because the video cable connected from the fpga board to the A-board was very near to the psu in the 128DCR. I turned the cable the other way so it goes on the opposite side of the psu and it changes nothing.
The PSU has been recapped as all the 128DCR....

I read about a 47pf fix or a fix from #38 but I can't find where are the exact infos.

Is it something I could try. 

Very strange because it can do this for a moment then stop for some times  then start again....

**Comment by c0pperdragon** [comment]
When the whole display is moving around slightly, this can not be caused by internal signals being miss-detected (the 47pf was a fix for this, but with the newest firmware this is also no longer necessary).

The problem is mist likely your monitor. Maybe you have different devices to this. Just some device with a simple composite video input will work when you just use the Y signal.

**Comment by c0pperdragon** [comment]
You should also try different output modes. You can switch between 240p/288p and 480p/512p with the mode selector.

**Comment by lolof70** [comment]
It's not really all that is moving, it's something like a noise on the picture.

Different output changed nothing, also tried with OSCC and the result was the same, even amplified.

I can't believe it....

The dcr was plugged  on a 220V power multi block...
I tried powering the C128 alone from another wall plug. No more on multi block....

It's working a lot better. this effect is almost gone... Just time to time but nothing as before when it happened...

Strange. I checked on the normal video din output, this effect are not to see.

It has probably something to do with PSU ?

**Comment by c0pperdragon** [comment]
Could you do some video capture with the PSU that causes the worse picture? I still can not quite visually imagine what you mean.

**Comment by lolof70** [comment]
Yes, done

https://youtu.be/xooaiQYsORM

I only have one PSU. The original recapped one.
This "movement" are less (but still visible sometimes) when the DCR is plugged to the 220V in a single 220V wall plug.

When it's plugged in a multi plug with other devices together, this is worst as on the video.

I also tried with another TV, it's the same. Just that the other TV is a lot smaller and because of this, it's not so visible as on a big screen, but it's there...

Touching the Module board replacement, just with a finger on the FPGA, can also make artefact on the screen but I can imagine that's normal because it changes resistance....

**Comment by c0pperdragon** [comment]
So, at least I see that it is no problem on the digital side between the C64 and the mod board. The problem here is some analog noise.  

Your experiement with touching was very important. It is absolutely not normal that such minor capacitive changes should cause any noticable difference on the screen. My only conclusion is that there is something faulty with the DAC resistors or the soldering of the FPGA pins. Maybe one of the many legs of the FPGA has no proper contact or some flux residue causes leakage current between pins or something like that.

**Comment by lolof70** [comment]
The board was put in a propanol ultra sonic bath. It's very clean.
I will check again the legs from the fpga. Which one are de DAC resistors ? 

Also... I build 2 board (I forgot this !!!!).. I will connect the second one and check if it does the same, also with touching...

**Comment by lolof70** [comment]
The problem with touching the FPGA is solved.
You were right ! I had 2 pins not well soldered on the FPGA... I missed them when I checked after soldering...

I checked again on my big TV who can do 240P.... Best results is using 240P and with the power cable alone in a 220V plug.
Probably same as before. 480P is always with this noise on big and small TV...

I will try to feed the video on the small TV through HDMI with OSCC and 240P from FPGA....  The small TV is the one I want to use with the 128... If it does as well as on the big TV 240P, I will be happy :-)

I still have to check if it does the same with the 2nd board I built...

Thanks again for your support.

Edit : Just by curiosity, I tried with another small TV in 420P and on this one it's very good... It seems to be also a TV problem. Out of 3, one work very well with 420P with the DCR power plug also in the multi plug.... !

**Comment by c0pperdragon** [comment]
So, if there is at least one TV that shows the picture perfectly, then the signal is obviously perfect already and no action is needed on part of the YPbPr mod.

**Comment by lolof70** [comment]
Yes, the mistake was the 2 pins not soldered on FPGA and a bad combination of TV during the tests.... 
I played already a lot with it, impressive with the right TV ! Thank you.

**Comment by mincebert** [comment]
I've been watching this (and the previous thread) hungrily, in anticipation for my 128DCR...

Does anyone know of someone selling these boards for the 128?  My soldering skills aren't up to something like this, so I was hoping someone would offer them, as per the C64.

Thanks in advance for any solutions!

**Comment by djcarlin** [comment]
I too am interested in purchasing a kit, for my C128 - similar to the C64 kit I bought from VGP.  Thanks!

**Comment by c0pperdragon** [comment]
As it currently looks, the global semiconductor shortage also hits us hobbyists pretty hard. The FPGA that is the central part of the mod is sold out and may become available again earliest 2022-7 (but no guarantees, of course). Even then I am not sure if I will have the time to take up soldering these FPGA boards anyway.

There may still be another option. The FPGA board from the C64 mod is basically identical to the shrunken-down version for the C128, So If you want to become creative, you could actually order a C64 mod from videogameperfection.com, discard the C64-VIC-adapter (a shame to waste it, but, well...). Then add a C128-VIC-adapter for which parts should still be fairly easy to get.  Fitting the C64-FPGA board into the C128 is probably quite difficult and may require cutting away some shielding metal, but I guess you could do that.
If you want to go that route, I could check if I can get all the parts for the adapter (still have 6 PCBs for that) and build these for a reasonable price.

**Comment by c0pperdragon** [comment]
You could actually ask user @bodgit if he has some kits remaining from his batch of 5 he made a few months ago. (https://github.com/c0pperdragon/C64-Video-Enhancement/issues/4).

**Comment by djcarlin** [comment]
Ideally, VGP could start carrying the C128 kit once the FPGA is available again in coming years?  @BuckoA511 expressed interest in carrying such a kit here:

https://github.com/c0pperdragon/C64-Video-Enhancement/issues/4#issuecomment-773215229

**Comment by bodgit** [comment]
Yes, I do have some spares still. I will email both @mincebert & @djcarlin to the address that is in your profile or commit history.

**Comment by mincebert** [comment]
> Yes, I do have some spares still. I will email both @mincebert & @djcarlin to the address that is in your profile or commit history.

Thanks — that's much appreciated!  (I don't think I was showing an email in my profile or if there was another way to contact me, but I think I am now.)

**Comment by bodgit** [comment]
> > Yes, I do have some spares still. I will email both @mincebert & @djcarlin to the address that is in your profile or commit history.
> 
> Thanks — that's much appreciated! (I don't think I was showing an email in my profile or if there was another way to contact me, but I think I am now.)

You hadn't, but I cloned one of your repos and used the email address you used for commits, it went to rcf@m****.net.

**Comment by bernouilli** [comment]
Hello,
I just found the great project and would like to get a kit for my c128.
Does anyone have any kit left?
Maybe @bogdit ?
Regards.

**Comment by bodgit** [comment]
I have my last two left now. From the old #4 issue I think @nickgoodmanuk wanted one as well so I'm tagging him as well. If you can let me know your email addresses (I can't see an address in your profile) I will contact you both with details.

**Comment by bernouilli** [comment]
That's perfect. Here is my email address : bernouilli**@***mail.com

**Comment by nickgoodmanuk** [comment]
Brilliant ! My email is nick@nickgoodman.plus.com.

Many Thanks.

**Comment by nickgoodmanuk** [comment]
> I have my last two left now. From the old #4 issue I think @nickgoodmanuk wanted one as well so I'm tagging him as well. If you can let me know your email addresses (I can't see an address in your profile) I will contact you both with details.

I'm another happy C128 component video customer !   Many thanks to @bodgit for building and sending me the boards and obviously @c0pperdragon for his design.   Fantastic picture!

![IMG20210816185658](https://user-images.githubusercontent.com/79846351/129690545-b0c5b207-4263-4eae-b7c7-d0e92080cab4.jpg)

![IMG20210816185640](https://user-images.githubusercontent.com/79846351/129690515-99954adc-3adc-4b2d-97c1-60b286e45347.jpg)

![IMG20210816185800](https://user-images.githubusercontent.com/79846351/129690556-4d722627-e4f4-4392-9a25-654f79593074.jpg)

![IMG20210816185648](https://user-images.githubusercontent.com/79846351/129690533-6dbfc146-d067-43fe-b1d8-678995fccd02.jpg)

![IMG20210816185806](https://user-images.githubusercontent.com/79846351/129690500-012551cf-255d-4ea8-a5a5-44605c8308c6.jpg)

**Comment by c0pperdragon** [comment]
Voll gerne  :-)

**Comment by mincebert** [comment]
I've now fitted mine from @bodgit and it works brilliantly in my 128DCR.

![IMG_6462](https://user-images.githubusercontent.com/21294069/130371440-1ac92cc0-fde4-4adf-b543-6e12ac1590b5.jpeg)

I thought I'd attach some pictures for reference, to show how I moved the capacitor adjacent to the VIC-IIe socket by putting some short wires in, to lay it behind the other one.

![IMG_6465](https://user-images.githubusercontent.com/21294069/130371229-0d04c9e2-bd66-4d76-b4c7-9c0b46dfa9e7.jpeg)

I then sawed the RF shield / heatsink cover in half so it just covers the 8568 VDC side.  I need to get some stick-on heatsinks for the VIC-IIe.

![IMG_6471](https://user-images.githubusercontent.com/21294069/130371299-4dbfaa54-2903-4b0d-aed5-cf933e626890.jpeg)

The only minor issue is the IDC connector into the CPLD board is _really_ tight up against the PSU tray: I have to connect the cable first, then drop that side of the PSU in and then press gently to get it to slot in on the other side.  This bends the socket a fraction of a millimetre:

![IMG_6472](https://user-images.githubusercontent.com/21294069/130371372-59b340f6-1fb1-4d61-a776-d2667870e43a.jpeg)

![IMG_6469](https://user-images.githubusercontent.com/21294069/130371509-debe6db1-e347-4dc7-9783-f9a7da3d388b.jpeg)

So, if there was an iteration of this, it would be good to shift the pins for the IDC connector on the CPLD board a little bit away from the PSU tray — probably 2-3mm would do it, but a little bit more would be even better.

I don't know if anyone else installing this has a DCR (or even a D) and had the same issue: the other ones I saw here were flat ones (I think @bodgit said his was a rare 128CR), so presumably they don't have this problem.

**Comment by mincebert** [comment]
Brief follow up on this, now I'm back from holiday and some final goodies have arrived...

I got a heatsink meant for an M2 SSD 70x22x6mm and it fits beautifully over the VIC-IIe and my multimeter's temperature probe shows the temperature around 36-37ºC on the middle (where I was getting 46+ºC on the bare chip):

![IMG_7379](https://user-images.githubusercontent.com/21294069/131862851-bb075be2-a990-4f3a-bf9f-601f55d00081.jpeg)

I also made up a TRRS-IDC cable to connect the board to a Raspberry Pi RGBtoHDMI with analogue board and YUV mode loaded onto the CPLD and a jumper across pins 9-10 on the JTAG connector to replace 576p scanline mode with the 288p high contrast palette:

![IMG_7378](https://user-images.githubusercontent.com/21294069/131862301-fb9df5b8-1276-415a-8626-f185a03e29cf.jpeg)

This is giving a beautiful image that you could forgive for being an emulator (this saved by the RGBtoHDMI directly, rather than grabbing the 1080p HDMI output, so it's a pure PNG of the source image):

![capture1](https://user-images.githubusercontent.com/21294069/131862566-5ef1be50-c745-4ff7-b93c-7bee75a323dd.png)

The only thing I had to tweak on the RGBtoHDMI was to lower the DAC-C UV Hi sampling setting to 052 (0.67V) to 035 (0.45V), otherwise various colours weren't detected correctly.  I don't know if that's normal for the C64 version.

Thanks everyone — this is absolutely amazing: I've gone from a flakey S-Video image with noise and flickery colours to a beautiful HDMI picture.

**Comment by rasivert** [comment]
Very interested in this, are there more available?

**Comment by bodgit** [comment]
> Very interested in this, are there more available?

I don't have any more left now, sorry. It might be a while before someone builds some more as last time I checked, the FPGA used has a very long lead time on it, (April 2022 I think).

**Comment by rasivert** [comment]
Oh, I see. Well I guess patience is the word here.

**Comment by cyberpax** [comment]
after being directed by videogameperfection.com to this project...
(see https://videogameperfection.com/forums/topic/c64-component-video-mod-will-it-work-on-a-c128/#post-44475)
I am also very interested in buying a board, to repair my c128 which apparently has damaged RF modulator. 
(last time I connected my c128 to an old TV via RF I couldn't get any picture ... all black) ...
Can this board solve my c128 problem ?! please advise?
I will wait as long as it takes for it !!!
it would be wonderful to have my c128 alive again!!! 
any advice and opinions would be appreciated !

**Comment by c0pperdragon** [comment]
A black screen can actually have many reasons. The RF modulator itself is normally pretty undestructible, so I very much guess it is some other issue (the PLA or the RAM or the VIC or the CPU or a multitude of other possibilities). You should really get the machine working in its normal condition before trying to upgrade the video output.

**Comment by Murphy-sudo** [comment]
Very interested I buying one as well when available 😊

**Comment by Jest0r** [comment]
Awesome work! I can't wait to get my hands on one for my C128DCR, too!

**Comment by honselio** [comment]
Hello, this is a great project! Just messing around with one of those boards, trying to get it work. All I can achieve ist this kind of wrong image:
![IMG_20211029_192415](https://user-images.githubusercontent.com/74380250/139478729-a03344cd-b629-4b0c-96ba-289715f449b5.jpg)
FPGA programming with quartus seems to work, no errors reported. Can someone kindly give me a hint into the right direction? Another board is already working on this monitor setup, so the Samsung monitor is not the problem..

**Comment by c0pperdragon** [comment]
As the content of the picture looks mainly OK, I would guess thath the connection between the C64 and the FPGA is working fine. So the fault probably lies in the video signal generation. I would guess that the csync signal is not mixed correctly into the Y output. With an oscilloscope you could easily check this. 
Otherwise check the signal path for the csync signal from pin 46 on the FPGA through R1 and see if all outputs of R1 - R6 are connected together.

**Comment by honselio** [comment]
Oha, checked R1, 130 Ohm instead of 1,1k Ohm, an angström solder bridge was the culprit. Board 2 is working. Vielen Dank und Grüße ins schöne Wien!

**Comment by Braincell1973** [comment]
Hi , are these boards available ? Or is there gerbers to have some made ??

**Comment by c0pperdragon** [comment]
The install consists of two parts which (for historical reasons live in different repos):
https://github.com/c0pperdragon/A-VideoBoard/tree/master/c64mod/c128board
https://github.com/c0pperdragon/C64-Video-Enhancement/tree/master/smallreplacement
So you can have your own PCBs made. But due to the global semiconductor shortage, the FPGA needed is not available (and probably will not be for a year or more). 

videogameperfection.com seems to have some C64 kits in stock. You could use this by replacing its VIC-II adapter with your home-made VIC-IIe adapter (link above) to fit the C128.  Also you need to find a way to fit the larger FPGA board into the smaller space of the C128. If this is too cumbersome, you will have to wait for the global delivery chains to fill up again...

**Comment by kavanoz64** [comment]
Using 2 of the 24 pin long tail sockets for VIC-IIe adapter would be easier and cost the same if you don't already have 40 pin. No cutting required.
https://www.mouser.com/ProductDetail/Mill-Max/111-93-624-41-001000?qs=WZeyYeqMOWdZSxh1h66G8A%3D%3D
https://www.digikey.com/en/products/detail/mill-max-manufacturing-corp/111-93-624-41-001000/260654

**Comment by djcarlin** [comment]
I finally got around to installing the C128 kit @bodgit sold me (thank you!!) and its working well.  I did have one question about s-video output.  I noticed it seems to have issues with the color "Red".  Top photo is S-VIdeo on Dell 2007FPb via OSSC & Koryuu:

EDIT: Red seems fine as long as background isn't "Dark Gray" ?  Just a VIC-II thing?

![IMG_5472](https://user-images.githubusercontent.com/16088593/147269942-33ed32ef-4d69-44d8-b11e-bca3cd6a75bf.JPG)

Second photo is same display, same OSSC - but no Koryuu -  using component output of C128 instead:

![IMG_5473](https://user-images.githubusercontent.com/16088593/147269930-7640fbaf-1024-4922-940f-b60eec291958.JPG)

**Comment by c0pperdragon** [comment]
The questionable quality of the original VIC signal (composite and s-video on the original A/V port) is the main reason to create component video from the digitial communication signals. 
The mod provides a high-quality video amplifier to make the best of the analog VIC output  to give you the best s-video and composite it can. I am quite surprised how well the image actually looks. 
Of course it can not reach the quality of the independently created component video signal.

**Comment by djcarlin** [comment]
I dug out a 64C shortboard and Red on Dark Gray looks just as bad via s-video.  

I love having emulator level picture quality on real hardware !  Thank You!

**Comment by ami-commo-fan** [comment]
> I don't have any more left now, sorry. It might be a while before someone builds some more as last time I checked, the FPGA used has a very long lead time on it, (April 2022 I think).

I would take one as well when bodgit builds some more.

**Comment by rasivert** [comment]
> > I don't have any more left now, sorry. It might be a while before someone builds some more as last time I checked, the FPGA used has a very long lead time on it, (April 2022 I think).
> 
> I would take one as well when bodgit builds some more.

Same here!

**Comment by themaddman** [comment]
> > Very interested in this, are there more available?
> 
> I don't have any more left now, sorry. It might be a while before someone builds some more as last time I checked, the FPGA used has a very long lead time on it, (April 2022 I think).

Add me to the interested list, if the FPGA ever becomes available again.

**Comment by Robert-Di-Benedetto** [comment]
I will take 2 of these when they become available again.

**Comment by johansmolinski** [comment]
I'd love an RGB board compatible with my C128DCR as well. Please sign me up if there is a list for that anywhere. :)

**Comment by johansmolinski** [comment]
It seems like the FPGA is actually available, for instance at these two shops:

https://www.win-source.net/products/detail/intel/10m02sce144c8g.html
https://www.utmel.com/productdetail/intel-10m02sce144c8g-7539873

I have no idea of the authenticity of these shops, nor whether the price is good or not. Just found they claim to have some in stock.

**Comment by bodgit** [comment]
They're charging between $75-$90 per chip (depending on quantity). They normally would be less than $10. That's quite a markup!

I think they are being produced, but they're being snapped up by volume buyers so there's none spare for people like us who are essentially hobbyists. I think I've purchased as many as 10 in one order, which is nothing really.

**Comment by johansmolinski** [comment]
Ok, I had no idea they originally were that cheap. Heck, an FPGA for less than $10?! Wow...

Do you have all other parts for what is needed to build a board that will fit inside a C128DCR?

**Comment by thepebbler** [comment]
> They're charging between $75-$90 per chip (depending on quantity). They normally would be less than $10. That's quite a markup!
> 
> I think they are being produced, but they're being snapped up by volume buyers so there's none spare for people like us who are essentially hobbyists. I think I've purchased as many as 10 in one order, which is nothing really.

I've just grabbed two C128's (A C128D and a regular C128) , both are broken, but the plan is to get the C128D resurrected and wanted to get a the small board version, but don't have the kit to solder the FPGAs on!

Is anyone planning on doing a batch? I might be able to help source the FPGA if that is the blocker, I can ask in work and get our CEM team (they work with our CEMs making our PCBAs) to see if they can source the FPGA at a reasonable price, and get some at cost.

**Comment by scorpio-ny** [comment]
Before I order a PCB, I wanted to check here to see  if anyone has an extra VIC-IIE PCB adapter or an extra assembled VIC II-E adapter they do not need and would be willing to sell? A while ago I had purchased a 64 kit from VGP in which I was saving for when I would get a C128 (finally acquired). Thank you!

**Comment by johansmolinski** [comment]
I am offering to trade a fully working C128 PAL with 6581, healthy yellowed, **without** PSU for a full c0pperdragon C128 kit that will fit inside my C128DCR. I can do whatever needed to fit it, if it means cutting things and relocating capacitors or whatnot, as long as the kit is complete. I live in Sweden, so I would prefer to do it within EU, but everything is possible.

**Comment by c0pperdragon** [comment]
c0pperdragon here.
Even I don't have any of those boards. But maybe you would be interested in
my follow-up product. It solves the same issue in a new way using a small
mod board and an external RGBtoHDMI. See https://github.com/c0pperdragon
for the C64 variant.
If there is demand, I could also make a C128 version.

Johan Smolinski ***@***.***> schrieb am Mi., 31. Mai 2023,
08:07:

**Comment by johansmolinski** [comment]
Thanks for prompt reply! Your link is to your profile. Which of the repositories are you referring to? And will it be usable for hooking up the C128 to a 15 kHz CRT on RGB? That's all I care about. :)

**Comment by c0pperdragon** [comment]
it is the wiki section of github.io  .
and currently the solution is for HDMI upscaling.
but maybe i can dream up some DIY circuit to get RGB again.

Johan Smolinski ***@***.***> schrieb am Mi., 31. Mai 2023,
10:08:

**Comment by rasivert** [comment]
> I could also make a C128 version. 

Very much interested in a C128 version!

**Comment by johansmolinski** [comment]
Would the RGB2HDMI be able to output 15 kHz, like "direct video" on MiSTer? If so, you could probably use a cheap HDMI to VGA adapter to get good 15 kHz RGB that way.

Still I don't find the information you are referring to. I would really appreciate a direkt link, please. :)

**Comment by c0pperdragon** [comment]
https://github.com/c0pperdragon/c0pperdragon.github.io/wiki/VIC-II-dizer

**Comment by c0pperdragon** [comment]
I hope, I do not give away confident information, but videogameperfection.com seems to be in the process to stocking up on the C64 variant of the mod.
Looking at the pictures of the C128DCR motherboard, at least the FPGA half of the mod may actually just fit.
Maybe someone has/can make a VIC-IIe pickup board. 

In case you can not get a suitable pickup board, you can even try a super-badass hack, I just came up with: Instead of putting a pickup-board between the VIC and its socket (which will only work when you have the correct board), you could instead piggy-pack the C64 pickup board onto the VIC. Most signals are at the same place, so you only need to cut away 6 of the pins and re-reoute these signals . If you want to go that way, I can give more detailed instructions.

**Comment by c0pperdragon** [comment]
I created a new thread for this topic, at this here is already much too long again:
https://github.com/c0pperdragon/C64-Video-Enhancement/issues/89
