### ISSUE TITLE
support for C64 Component Mod

### ISSUE THREAD

**Issue by tronarea** [c0pperdragon/C64-Video-Enhancement#65]
I install the fpga board and the VIC II Adapter, i replace the c64 VIC II ic holder and replace with a drilled 
precision IC holder and the picture its generate was perfect wonderfull!!!
 
But on jump and run example giana sister the green woods change from green to white also on x-out sprites.
 
My setup c64 with vic II you can see the model also on pictures.
 
 
What can i do, i love the modul its so clear picture but with the grafic errors i cant use it so.
 
Im a electronic specalist with good skills i know all about esd and so on i was realy carrfully with this board.
 
Thanks for your time i hope you can help

Best regards Jürgen 

![1](https://user-images.githubusercontent.com/83313426/116313606-45ac4d00-a7ae-11eb-9f79-476b7db52b9a.jpg)
![2](https://user-images.githubusercontent.com/83313426/116313609-46dd7a00-a7ae-11eb-8c60-425671b343e3.jpg)
![IMG_20210427_203831](https://user-images.githubusercontent.com/83313426/116313612-46dd7a00-a7ae-11eb-99bf-410375d5c93d.jpg)
![IMG_20210427_205208](https://user-images.githubusercontent.com/83313426/116313614-47761080-a7ae-11eb-9f3b-7b56b9d415c2.jpg)
![IMG_20210427_205212](https://user-images.githubusercontent.com/83313426/116313618-480ea700-a7ae-11eb-852f-69bd22066d76.jpg)
![IMG_20210427_205215](https://user-images.githubusercontent.com/83313426/116313626-493fd400-a7ae-11eb-8b1d-0d75edadb403.jpg)
![IMG_20210427_215008](https://user-images.githubusercontent.com/83313426/116313628-493fd400-a7ae-11eb-81b6-35ff3628a371.jpg)
![IMG_20210427_215010](https://user-images.githubusercontent.com/83313426/116313632-49d86a80-a7ae-11eb-9c95-846464dfa35b.jpg)
![IMG_20210427_215011](https://user-images.githubusercontent.com/83313426/116313634-4a710100-a7ae-11eb-9c90-8013bf7a6680.jpg)
![IMG_20210427_215013](https://user-images.githubusercontent.com/83313426/116313635-4b099780-a7ae-11eb-8cdc-32a142979e43.jpg)
![IMG_20210427_215014](https://user-images.githubusercontent.com/83313426/116313638-4b099780-a7ae-11eb-9c19-6c14edef5716.jpg)

**Comment by c0pperdragon** [comment]
This is a pretty unusal effect. I looks like exactly this 8 pixel height stripe near the bottom of the screen is affected. For me this looks a bit like if the color ram of the C64 is somehow misbehaving.   
Could you check this by doing a direct comparision with the original video signal from the A/V port?

**Comment by tronarea** [comment]
First of all, many thanks for the quick response!

That is a good idea, unfortunately I have no connection option.

then tried to connect the video out via scart to the ossc scandoubler, unfortunately without success.

then processed the c64 chips with cold spray as well as with heat gun.

One was sensitive. I will desolder the vram from an existing device and install it in mine.

For your good idea you have to
do I have to fall back on a colleague who still has a tv with a connection. he is currently on vacation so it will not be possible to continue until next week.

thanks for the idea, I'll get in touch with the results next week.

have a good time and see you soon

best regards

jürgen

**Comment by tronarea** [comment]
Hello again, 


on the video out also have the video problem see attached photo

I think it's a problem on my c64 the multi chip 251715-01 is maybe defect.

thanks so much for your time

I think I must replace my c64? 

have a good time

best regards
Jürgen
![IMG-20210505-WA0001](https://user-images.githubusercontent.com/83313426/117165879-29b83500-adc6-11eb-9ec3-e75c9323e8e8.jpg)
