### ISSUE TITLE
Will it fit 250407 rev.B

### ISSUE THREAD

**Issue by magazaki** [c0pperdragon/C64-Video-Enhancement#66]
Hi

My board is 
Commodore 64
1983
Assy No. 250407
Artwork no.251137 Rev.B

VIC chip:
MOS 6569r1
2381
40 pins
12Volts

Seems like it could be an issue fitting the adapter, possible conflict with adjustable resistor and capacitor?
![MOS 6569r1](https://user-images.githubusercontent.com/24221840/118885466-180f7b00-b8f8-11eb-9365-19db75a4aff9.jpg)

**Comment by c0pperdragon** [comment]
There are a few difficulties to overcome with this specific board. One user made a nice video using this:
https://www.youtube.com/watch?v=oo_gWjK-gGw&t=534s
He also uses an additional hardware to then convert the output signal to HDMI, but this is optional of course.

**Comment by magazaki** [comment]
Great, thanks alot! I will give this a try!

**Comment by magazaki** [comment]
:)
