### ISSUE TITLE
Alternative part for Altera 10M02SCE144C8G?

### ISSUE THREAD

**Issue by modeler** [c0pperdragon/C64-Video-Enhancement#68]
Presumably due to the global chip shortage, the FPGAs listed in the BOM are showing as unavailable everywhere with long lead times. Mouser does not expect any significant stock of these until May 2022!

Could there be an alternative FPGA with the same footprint or is this project effectively stranded? Any advice would be most appreciated. Thanks in advance!

**Comment by c0pperdragon** [comment]
That is a real problem right now. Not only this specific part, but basically the whole chip family is sold out. It seems there are some remaining parts with 16k gates upwards (instead of the 2k), but they cost much more and are not immediately compatible. You would need to modify the PCB to make them fit. Also you need to adjust the firmware to the changed pinout.  All this is quite a major task and not cheap either (€44 instead of €6 for the FPGA alone).

**Comment by c0pperdragon** [comment]
If you are quick, you may get the last assembled board that is available from https://videogameperfection.com/products/commodore-component-video/

**Comment by modeler** [comment]
Thanks for the reply c0pperdragon. Unfortunately VGP don't ship to the UK due to Brexit issues, I have been talking to Matt on Twitter about this.

**Comment by modeler** [comment]
Quick update, VGP resolved their issue with UK customs and are shipping again. I was able to source a mod board and fitted it a few weeks ago, it is amazing. I would love to build some of these myself, I had the PCBs made and sourced all the parts... except the actual FPGAs. I really don't know when we're likely to find them for sale again.

![image](https://user-images.githubusercontent.com/3359889/134471320-8b1ef1c8-4651-4093-aeb6-8dad05317048.png)

**Comment by c0pperdragon** [comment]
Sorry, there is basically no replacement that fits the current PCB design. At mouser there are not even the more expensive parts that could be made to fit by slightly redesigning the PCB. 
I guess we have the same problem here as the global automotive industry...

**Comment by modeler** [comment]
Please don't apologise, this is not in any way your fault. I hope that at some point before VGP's stock runs out, we will all be able to source some of these FPGAs.
