### ISSUE TITLE
Firmware source code?

### ISSUE THREAD

**Issue by mwedmark** [c0pperdragon/C64-Video-Enhancement#69]
Is the firmware from https://github.com/c0pperdragon/A-VideoBoard.git usable directly out of the box? I don't understand where the code to build the Quartus project for this board is.. Thanks in advance, great work! Sorry to see shortage of circuits puts eveything to a halt, but lets it's getting better.

**Comment by c0pperdragon** [comment]
Ho to the subfolder for

**Comment by c0pperdragon** [comment]
Should not use github from a mobile... 
Anyway, go to the subfolder for the C64 mod. There is the Quartus project.

**Comment by mwedmark** [comment]
Thank you! I got 95% usage when building it in latest Quartus, that is a great Device/Project match! :-)

**Comment by c0pperdragon** [comment]
Yes it is a tight fit. Had to restructure the firmware a few times along the way to stay inside the bounds.
