### ISSUE TITLE
Picture is grayscales and not in colour!

### ISSUE THREAD

**Issue by sid978** [c0pperdragon/C64-Video-Enhancement#72]
After having installed Copperdragon board on my c64c (rob taylor) by commodore repairers (IBM?), the picture quality is grey scales. The repairers are suggesting that the tv (NEW) is running at different Hz frequency.

![COPPERDRAGON1](https://user-images.githubusercontent.com/77835044/138582249-53c3437a-445c-4ff5-a318-f335197171a2.JPEG)
![COPPERDRAGON2](https://user-images.githubusercontent.com/77835044/138582254-7de672fe-14db-40fd-a475-a65b1b525fe3.JPEG)
![COPPERDRAGON3](https://user-images.githubusercontent.com/77835044/138582257-f27993ba-2bc9-4bd9-a5a7-9cdaa2cbdb7e.JPEG)
![COPPERDRAGON4](https://user-images.githubusercontent.com/77835044/138582266-7a8451e3-7142-4b81-90a8-8bd534fbb794.JPEG)

**Comment by c0pperdragon** [comment]
The need to know that the component video signal that comes out of the mod board uses three lines to transport the video information: luminance (the brightnes information + sync) on the green plug and two color difference signals on the blue and red plug. This must not be confused with a composite signal (yellow plug) that carries all the information mixed together on a single line. 
By having this seperation, the quality can be much higher than with composite.  But you need  TV that accepts these three signals.

**Comment by sid978** [comment]
The original A/V output (5 pin Din) works correctly(color and sound) but the copperdragon does not! Pls explain?

**Comment by c0pperdragon** [comment]
Please try to understand what component video acually is. Try this wikipedia page: https://en.m.wikipedia.org/wiki/Component_video
