### ISSUE TITLE
Troubleshooting help

### ISSUE THREAD

**Issue by mwardy1972** [c0pperdragon/C64-Video-Enhancement#75]
I’ve had the component video mod from videogameperfection.com for a couple of months now and it's been working great ! But just the other day I turned on my c64 and the component output has stopped working.  The composite video output works fine. I just get a blank screen from the component output. Also, after a few moments the TV says ‘no signal’ when using the component output. I tried another tv in the house, same result. Unplugged the vic adapter board and ribbon cable, re-seated to be sure, still no go. A quick check with the multimeter, the voltage regs are putting out spot on 3.3V. I’m at a bit of a loss now trying to trouble shoot. I thought of getting a USB Blaster and trying to re-install the firmware ? Any ideas how to fix this ? Thankyou !

(my c64 board is 250469 Rev A and my VIC chip is 85652R2)

**Comment by c0pperdragon** [comment]
If it suddenly stopped working this is probably a hardware fault. I don't think re-installing the firmware will do any good.  
This now may sound stupid, but have you possibly changed the position of the output mode switch to a mode your TV can not display? 

Now seriously: Troubleshooting the device without a means to see the signals is pretty impossible. As you have no oscilloscope we need to get creative here. You can use your working composite output image and super-impose any digital signal by coupling the signal into the analog video output.
Try this: Use a simple resistor with about 4.8K and feed the signal you want to probe through this resistor into the junction point of R30,R31,R32 on the FPGA board. The best access to this point is at the side of R32 that is pointed towards the video amplifier AMP2.
To see if this rig works, start by probing pin 17 on the VIC-II itself, which is the system clock.  You should see very distinct vertical stripes (4 pixels light, 4 pixesl dark) on your video display.

If this works, try probing all the signals that come trough the ribbon cable from the adapter board. All pins besides 15 and 16 should have at least some activity when in the C64 start screen. 
Please report back then.

**Comment by mwardy1972** [comment]
Hi ! thanks for the help, I really appreciate it.  So, using your guidance and a bit of troubleshooting myself, I have found that U2, the 3.3V voltage regulator on the VIC adapter board is not functioning.  

As you suggested, I got a nice strong clock signal on pin 17 of the VIC-II.  But I didn't have anything on the ribbon cable at all.  I probed onto the VIC-II on the equivalent pins (i.e. DB0-DB11, A0-A5) and got the activity you described.  Which led me to review the schematic for the adapter board and I found I had missed testing this voltage regulator initially. I checked it and found pin 5 had no voltage.  So to test it, I placed a bridge over to the output of REG 2, and ..... YES !! it works now.  I found the problem, U2 is dead.  Now I just have to work out how to replace it, it is tiny.  Thankyou.

**Comment by c0pperdragon** [comment]
My congratulations! Nice to hear that this impromptu oscilloscope actually worked. 

The voltage regulator on the adapter board is indeed pretty tiny. If you don't mind a bit of a mess and the damaged regulator is not interfering otherwise, you could leave it in and just wire a larger regulator to the capacitors directly.

**Comment by mwardy1972** [comment]
I've managed to do a fairly neat job using a MCP1700-3302E 3.3V regulator.  Working great.  Might be helpul if anyone else experiences this issue.

![20211207_192336](https://user-images.githubusercontent.com/94768526/144993085-5f07aa09-17b6-4761-a3e9-78d8c56e2efb.jpg)
