### ISSUE TITLE
CMOS or NMOS?

### ISSUE THREAD

**Issue by pushead** [c0pperdragon/C64-Video-Enhancement#77]
Hi,

Hope I can get some advice from you:)

I'm going to install the RF modulator replacement for my C64C. But although this is a C64C is does have the longboard (assy 250466) and have the nice VIC-II 6569R5. But I'm not quite sure if this is a NMOS or CMOS? I beleive I need to know this in order to solder the JPLUM1 or not?

All the best!

**Comment by laubzega** [comment]
It's NMOS.

**Comment by c0pperdragon** [comment]
The long boards run with the higher voltages (all VICs with a number starting with a "6"). So you need to close the solder bridge in order to get propper luma levels. If you don't do this, nothing bad will happen, only giving you unusual luminance intervals on the image.

**Comment by pushead** [comment]
Ah, I see! Thanks for helping me!

Have a nice holiday!



tor. 23. des. 2021 kl. 15:50 skrev c0pperdragon ***@***.***>:
