### ISSUE TITLE
Grey dot bug is not reproduced?

### ISSUE THREAD

**Issue by modeler** [c0pperdragon/C64-Video-Enhancement#92]
Hi,

This is more of an observation than an issue, but I noticed that the grey dot bug (or gray dot bug depending on your dialect) found in the later VIC-II models e.g. MOS 8565 is not reproduced by the FPGA. This is noticeable as 'snow' on the title screen in _Great Giana Sisters_ and other programs, but there is even a demo that uses it to draw star fields and vertical lines:

https://csdb.dk/release/?id=233555

I am interested to know if this was a conscious decision and if there is any scope for enabling it in software at some point? For the record I would prefer to keep it turned off to be honest, so please don't take this as a complaint of any kind.

Thanks!

**Comment by c0pperdragon** [comment]
I know of this white point but, but I just didn't want to bother trying to simulate this. Anyway, as it is, the FPGAs logic fabric is completely filled up, so there is no room for new features, anyway.

**Comment by modeler** [comment]
No problem, if anything I just wanted to document that the bug is not there. Thanks again for your support.
