### ISSUE TITLE
Analog only on C128 dark border

### ISSUE THREAD

**Issue by mmiletta** [c0pperdragon/C64-Video-Enhancement#93]
Hi,
I've installed the analog_only board on a C128 and I'm dealing with a weird dark border/shadow as you can see in the images.
I noticed it on the C64 mode in the right border but then I checked the C128 image and I can see something similar happening on the left side.
I've replaced all the electrolytic caps just in case and also the trimmer C20, but no luck so far.
Do you know what could be the issue or what test I can do?
The image is coming from a Samsung LCD TV connected to the composite output.
Thanks in advance! 
![IMG_2704](https://github.com/c0pperdragon/C64-Video-Enhancement/assets/5452620/00b0bd00-df6d-4e78-8008-d6457e3af7a7)
![IMG_2702](https://github.com/c0pperdragon/C64-Video-Enhancement/assets/5452620/589eb367-27d9-462c-bb16-0085ddc95e6e)

**Comment by c0pperdragon** [comment]
Hard to tell without an actual oscilloscope session. Maybe an extreme case of interference from some signal line. Or your TV does some crazy stuff.

**Comment by mmiletta** [comment]
I've tried with a different RF modulator and having the same problems so it's not about the mod.
All electrolytic caps in the board and also in the psu have been replaced.
If you have any idea about what I can check please let me know. 
Closing the issue, thanks!
