### ISSUE TITLE
576p modes via RGBns (SCART)

### ISSUE THREAD

**Issue by modeler** [c0pperdragon/C64-Video-Enhancement#94]
Hi,

I built a SCART cable using CSYNC (and +5V to pin 16) from the A/V port and switched the output to RGBns. I get a good result on my two LCD TVs (one is LG, the other is Sony) in 288p mode apart from the deinterlacing artefacts, but if I switch to 576p I get horizontal doubling like this:

![IMG_20231020_083906534](https://github.com/c0pperdragon/C64-Video-Enhancement/assets/3359889/d63f953e-2643-4d47-b390-09c4f97e107a)

It's the same on both TVs, however the LG TV has component / YPbPr inputs on the back and if I use these with the firmware defaults it is fine (my RetroTink 2X shows a similar doubling effect though, which I guess is expected). I am wondering if there is anything I can do about this, or whether it's just a limitation of the TV in both cases? Neither TV supports sync-on-green though, sadly.

The FPGA board itself is clearly outputting these modes correctly for YPbPr, but I would like to confirm if these modes are supported for RGBns?

Thanks in advance!

**Comment by modeler** [comment]
According to this old thread, 576p via SCART input isn't a thing:

https://www.avforums.com/threads/576p-via-scart.770421/

This answers my question I guess, in that it's not supported by SCART regardless of the device connected to it. But it would be good to confirm. Would this also apply to sync-on-green?

**Comment by c0pperdragon** [comment]
As far as I know, SCART inputs (RGBS) are specified for SDTV with 15kHz horizontal scan rate). Faster analog signals (EDTV) use double the horizontal scan rate and are only specified for Component Video. What the individual TV is capable of is of course a totally different matter.

**Comment by c0pperdragon** [comment]
sync-on-green is basically a proprietary Sony technique for their high end analog RGB monitors. Totally depends on the monitor in question.

**Comment by modeler** [comment]
Thank you for explaining, I am not exactly an A/V guru but I've learned a lot about the subject from this project.
