### ISSUE TITLE
Rev. 6 died after flashing v2.11

### ISSUE THREAD

**Issue by shindouj** [c0pperdragon/C64-Video-Enhancement#99]
Hi there,

I have finished assembling my Rev. 6 C64 Video Enhancement yesterday and got to the point of it working with the test firmware - got perfect gradients and a stable signal - so I decided it is okay to go ahead and flash the final firmware onto the FPGA. 

Right away after programming the chip the JTAG stopped working (Quartus complains about JTAG chain - like the chip was not there). There was no component signal either. I have assembled and plugged the daughterboard in since then and it did not change (no signal, no JTAG). However, the analog part is working - I am still getting composite output.

Do you have an idea what might be the issue here? I think nobody here had a similar issue, at least it's not something I have found while browsing through issues...

Thanks a lot for your support.

![20231124_135502](https://github.com/c0pperdragon/C64-Video-Enhancement/assets/4504156/a56b94bc-20ff-4d65-82bd-cfe890362af4)
![20231124_135549](https://github.com/c0pperdragon/C64-Video-Enhancement/assets/4504156/948f111a-97d8-4d7d-bdcd-a4ba8f753daf)
![20231124_135452](https://github.com/c0pperdragon/C64-Video-Enhancement/assets/4504156/7eed91eb-c785-4d8f-b3f0-c1cea7b9f3b2)
![20231124_135443](https://github.com/c0pperdragon/C64-Video-Enhancement/assets/4504156/ea75ffac-0b7e-4ced-9332-a47567028183)

**Comment by c0pperdragon** [comment]
Flashing the firmware has serious challenges.  Maybe something in these threads may help you:
https://github.com/c0pperdragon/C64-Video-Enhancement/issues/80
https://github.com/c0pperdragon/C64-Video-Enhancement/issues/97

**Comment by shindouj** [comment]
Thanks, but I think we misunderstood each other.

I have successfully flashed the firmware already - quite a few times, actually. Right after building the board I have flashed [the pattern generator](https://github.com/c0pperdragon/A-VideoBoard/releases/tag/1.1) at least three times. My USB blaster is detected just fine, and I used Prime 18.1 as suggested. That step worked flawlessly, and after flashing the firmware, a pattern has been generated.

However, after _successfully_ (according to Prime) flashing the [video enhancement 2.11 firmware](https://github.com/c0pperdragon/C64-Video-Enhancement/releases/tag/2.11) the board became essentially dead, with the JTAG header apparently not working anymore - something that did not happen with the pattern generator firmware. This has happened immediately after flashing - when flashing was completed at 100%, I opened the programmer again, and it was not able to recognize the chip anymore.

I don't think this is an issue with my blaster or my programming setup since that has succeeded before (and by before, I mean 12 hours ago - when flashing the pattern generator).

**Comment by shindouj** [comment]
Update: I have found a severed trace from RFCON2_1 to REG1_3 - bodged it, mod outputs video now. I think I have severed it when I was moving the board a little bit higher. I'm relieved that I did not brick it by flashing, at the very least.

...But JTAG is still not functional. It'd be good to make it work for any future firmware upgrades - do you have any ideas what might've caused that outage?

**Comment by c0pperdragon** [comment]
The real firmware (in contrast to the pattern generator) shares the JTAG pins for some functionality. So it may very well be that this is now conficting with the programmer to prevent further access to it. Using the software and hardware mentioned in the other threads on this topic seems to overcome this problem somehow.

**Comment by shindouj** [comment]
Oh, understood. That may be very well the case. Well - I'm off to doing a proper fix for that trace, and thanks for your hard work on the mod! I'm impressed I managed to make it work at all, it was my second time doing any SMD soldering at all 😅

**Comment by c0pperdragon** [comment]
Wow! Going from 0 to 144 pin, 0.5mm is a pretty steep learning courve.
